apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jrsz7n4pm-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jrsz7n4pm-python 
  name: jrsz7n4pm-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jrsz7n4pm-python 
